apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: smokeping-claim0
  name: smokeping-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
