apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: smokeping-claim1
  name: smokeping-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

